db:
  url: "jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?user=postgres.mptznakdosophrvmvuzs&password=Good@123SKSKS"
  driver-class-name: "org.postgresql.Driver"
  user: "postgres.mptznakdosophrvmvuzs"
  password: "![lb/bsKNO73yh6CvHqVCrMQ==]"
  
sf:
  username: "birundha.0e835ae91770@agentforce.com"
  password: "Bru@1234"
  security-token: "8XlqyasEcrtqXt0z8LrQnB23"
  url: "https://login.salesforce.com/services/Soap/u/64.0"
  
  